In [1]:

%load_ext tensorboard

In [2]:
import tensorflow as tf
import datetime

In [3]:
# Clear any logs from previous runs
!rm -rf ./logs/ 

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [9]:
len(x_test)

10000

In [10]:
len(x_train)

60000

In [5]:
def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

In [6]:
model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(x=x_train, 
          y=y_train, 
          epochs=5, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback])

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 7s 120us/sample - loss: 0.2181 - accuracy: 0.9358 - val_loss: 0.1057 - val_accuracy: 0.9690
Epoch 2/5
60000/60000 [==============================] - 7s 112us/sample - loss: 0.0962 - accuracy: 0.9705 - val_loss: 0.0768 - val_accuracy: 0.9754
Epoch 3/5
60000/60000 [==============================] - 7s 121us/sample - loss: 0.0695 - accuracy: 0.9783 - val_loss: 0.0725 - val_accuracy: 0.9781
Epoch 4/5
60000/60000 [==============================] - 10s 164us/sample - loss: 0.0535 - accuracy: 0.9829 - val_loss: 0.0739 - val_accuracy: 0.9777
Epoch 5/5
60000/60000 [==============================] - 9s 156us/sample - loss: 0.0452 - accuracy: 0.9852 - val_loss: 0.0767 - val_accuracy: 0.9772


In [13]:
len(x_train)

60000

In [15]:
x_train[0].shape

(28, 28)

In [17]:
len(y_train)

60000

In [18]:
y_train.shape

(60000,)

In [21]:
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test))


In [34]:
kk = list(train_dataset)

In [37]:
kk[9][1]

<tf.Tensor: shape=(), dtype=uint8, numpy=4>

In [38]:

train_dataset = train_dataset.shuffle(60000).batch(64)
test_dataset = test_dataset.batch(64)


In [20]:
train_dataset

<BatchDataset shapes: ((None, 28, 28), (None,)), types: (tf.float64, tf.uint8)>

In [41]:
list(train_dataset)

[(<tf.Tensor: shape=(64, 28, 28), dtype=float64, numpy=
  array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         ...,
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
         