In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
import numpy as np
import matplotlib.pyplot as plt
import os
from tqdm import tqdm
tf.keras.backend.set_floatx('float64')
from misc import *
from collections import deque
from nets import Q1, Actor
import random


import tensorflow as tf
from tensorflow.keras.layers import Dense
import numpy as np
import matplotlib.pyplot as plt
import os
from tqdm import tqdm
tf.keras.backend.set_floatx('float64')
from misc import *
from collections import deque
from nets import Q1, Actor, Q2
import random

In [19]:

class Q2(tf.keras.Model):
    def __init__(self):
        super(Q2,self).__init__()

        self.l1 = Dense(10, input_shape=(2,),kernel_initializer=tf.random_uniform_initializer(),
        bias_initializer = tf.random_uniform_initializer(),
        kernel_regularizer=tf.keras.regularizers.l1(0.01),
    activity_regularizer=tf.keras.regularizers.l2(0.01))

        self.l2 = Dense(33, kernel_regularizer=tf.keras.regularizers.l1(0.01),
    activity_regularizer=tf.keras.regularizers.l2(0.01),
    kernel_initializer=tf.random_uniform_initializer(),
    bias_initializer = tf.random_uniform_initializer())
        self.l3 = Dense(33, kernel_regularizer=tf.keras.regularizers.l1(0.01),
    activity_regularizer=tf.keras.regularizers.l2(0.01),
    kernel_initializer=tf.random_uniform_initializer(),
    bias_initializer = tf.random_uniform_initializer())
        self.l5 = Dense(2, kernel_regularizer=tf.keras.regularizers.l1(0.01),
    activity_regularizer=tf.keras.regularizers.l2(0.01),
    kernel_initializer=tf.random_uniform_initializer(),
    bias_initializer = tf.random_uniform_initializer())

    def call(self, input):
        feat = tf.nn.relu(self.l1(input))
        feat = tf.nn.dropout(feat, rate=0.01)
        value = tf.nn.sigmoid(self.l5(feat))
        return value

    def predict(self, history_one):
        inp = np.expand_dims(history_one, axis=0)
        return np.squeeze(self(inp).numpy())

    def initialize(self):
        inp = np.expand_dims(np.array([[0.],[0.]]),axis=1)
        self(inp)
        return

    def __str__(self):
        return self.name


In [20]:

def real_training(run_id, lr = 10**-2,
 states_wasted=10**3, batch_size=64, epochs=10, buffer_size=10**3, predict_q_table=True):

    q1=Q1()
    q2=Q2()
    actor = Actor()

    optimizer_critic = tf.keras.optimizers.Adam(lr = lr)
    optimizer_actor = tf.keras.optimizers.Adam(lr = lr)
    optimizer_l2 = tf.keras.optimizers.Adam(lr = lr)

    pt=[]
    rt=[]
    rts = []
    loss_ev = []
    history_betas = []
    history_would_have_done=[]

    betas_test = np.arange(-1,0,.05)
    optimal = max(ps_maxlik(betas_test))
    buffer = ReplayBufferKennedy(buffer_size=buffer_size)

    for episode in tqdm(range(states_wasted)):

        phase = np.random.choice([-1,1])

        beta_would_do = np.squeeze(actor.give_action().numpy())
        g=[]
        for n1 in [0,1]:
            g.append([-1,1][np.argmax(np.squeeze(q2( np.expand_dims(np.array([[beta_would_do, n1]]) ,axis=1 )).numpy()))])

        beta = beta_would_do + np.random.uniform(-.5,.5)
        history_betas.append(beta)
        history_would_have_done.append(beta_would_do)

        outcome = give_outcome(phase*0.4, beta)
        if np.random.random()<0.1:
            guess = np.random.choice([-1,1],1)[0]
        else:
            predictiones_guess = np.squeeze(q2( np.expand_dims(np.array([[beta, outcome]]) ,axis=1 )).numpy())
            guess = [-1,1][np.argmax(predictiones_guess)]

        pt.append(ps(beta_would_do,g))
        if guess == phase:
            reward=1
        else:
            reward = 0

        rt.append(reward)
        rts.append(np.sum(rt))
        buffer.add(beta, outcome, guess, reward)

        actions_did, outcomes, guessed, rewarded = buffer.sample(batch_size)

        histories = np.array([[be, out] for be, out in zip(actions_did, outcomes)])

        if episode%10 ==0:
            print("******")
            print("******")

            betass = np.arange(-1,0,.1)

            shistory = []
            for b in betass:
                shistory.append([[b, 0.]])
                spred_guess_0 = np.squeeze(q2(np.expand_dims(np.array(shistory), axis=1)).numpy())
            print(spred_guess_0)

        if episode >0:

            with tf.GradientTape() as tape:
                tape.watch(q2.trainable_variables)
                predictions_l2 = q2(np.expand_dims( histories, axis=1))
                #loss=tf.keras.losses.binary_crossentropy(np.expand_dims(rewarded,axis=1), predictions_l2)
                loss = tf.keras.losses.MSE(np.expand_dims(rewarded,axis=1), predictions_l2)
                loss = tf.reduce_mean(loss)
                grads = tape.gradient(loss, q2.trainable_variables)
                optimizer_l2.apply_gradients(zip(grads, q2.trainable_variables))

            with tf.GradientTape() as tape:
                tape.watch(q1.trainable_variables)
                predictions = q1(np.expand_dims(np.array(actions_did),axis=1))
                
                next_predictions= np.squeeze(predictions_l2.numpy())
                print(next_predictions)
                next_greedy_predictions=[]
                for k in range(len(next_predictions)):
                    next_greedy_predictions.append(np.max(next_predictions[k]))
                print(next_greedy_predictions)
                print("          ")
                print("chechehcehchehchhcehceh")

                loss_sum = tf.keras.losses.MSE(np.expand_dims(np.array(next_greedy_predictions),axis=1),predictions)
                loss = tf.reduce_mean(loss_sum)
                grads = tape.gradient(loss, q1.trainable_variables)
                optimizer_critic.apply_gradients(zip(grads, q1.trainable_variables))
                loss_ev.append(np.squeeze(loss.numpy()))
    #
            with tf.GradientTape() as tape:
                actions = actor(np.expand_dims(np.zeros(batch_size),axis=1))
                tape.watch(actions)
                qvals = q1(actions)
            dq_da = tape.gradient(qvals, actions)

            with tf.GradientTape() as tape:
                tape.watch(actor.trainable_variables)
                actions = actor(np.expand_dims(np.zeros(batch_size),axis=1))
                theta = actor.trainable_variables
            da_dtheta = tape.gradient(actions, theta, output_gradients=-dq_da)
            optimizer_actor.apply_gradients(zip(da_dtheta, actor.trainable_variables))

    rtsum = rts/np.arange(1,len(rts)+1)
    if predict_q_table:
        predictions = np.squeeze(q1(np.expand_dims(np.array(betas_test),axis=1)).numpy())
        history = []
        history_1 = []

        for b in betas_test:
            history.append([[b, 0.]])
            history_1.append([[b,1.]])
        pred_guess_0 = np.squeeze(q2(np.expand_dims(np.array(history), axis=1)).numpy())
        pred_guess_1 = np.squeeze(q2(np.expand_dims(np.array(history_1), axis=1)).numpy())
        pred_guess = [pred_guess_0, pred_guess_1]

    plot_evolution_vKennedy_last(rt=rtsum, pt=pt, optimal=optimal, betas=betas_test,
     preds=predictions , pred_guess = pred_guess, loss=loss_ev, history_betas=history_betas, history_would_have_done=history_would_have_done,
      run_id= run_id)
    #
    save_models(run_id, models=[q1,q2,actor])
    data = "buffer_size: {}\Batch size: {}\nLearning_rate: {}\nOptimizer Critic: {}\nOptimizer Actor: {}".format(str(buffer_size), str(batch_size), str(lr),optimizer_critic.__str__(),optimizer_actor.__str__()  )
    #
    os.chdir(run_id)
    with open("info.txt", 'w') as f:
        f.write(data)
        f.close()
    os.chdir("..")

    return q1, q2, actor


check_folder("mate")

run_id=record()
number_run = "run_"+str(run_id)
q1, q2, actor = real_training(run_id=number_run, lr=1e-2,
 states_wasted=10**2, batch_size=1000, buffer_size=2*10**3)


  2%|▏         | 2/100 [00:00<00:06, 14.09it/s]

******
******
[[0.51152975 0.50286901]
 [0.51154317 0.50281905]
 [0.51155659 0.50276908]
 [0.51157    0.50271912]
 [0.5115795  0.50266244]
 [0.51157539 0.50258238]
 [0.51157127 0.50250233]
 [0.51156172 0.50241532]
 [0.51152348 0.50229161]
 [0.51148524 0.50216789]]
[[0.5111035  0.50306193]
 [0.51157104 0.50249774]]
[0.5111034962782872, 0.5115710355942864]
          
chechehcehchehchhcehceh
[[0.50818617 0.49980666]
 [0.50821564 0.49971585]
 [0.50719308 0.50033007]]
[0.5081861698145073, 0.5082156400755188, 0.507193083804113]
          
chechehcehchehchhcehceh
[[0.51042977 0.50192093]
 [0.51041038 0.5019891 ]
 [0.50976029 0.50260108]
 [0.51040552 0.50200619]]
[0.5104297668830883, 0.5104103787040674, 0.5097602948543423, 0.5104055163891701]
          
chechehcehchehchhcehceh


  6%|▌         | 6/100 [00:00<00:06, 14.93it/s]

[[0.51301149 0.50422354]
 [0.51272574 0.50485898]
 [0.51300362 0.50424994]
 [0.51300075 0.50425491]
 [0.51269071 0.50491963]]
[0.5130114908131069, 0.5127257411019838, 0.513003619335974, 0.513000749606189, 0.5126907109706118]
          
chechehcehchehchhcehceh
[[0.51543545 0.50639663]
 [0.51543643 0.50641049]
 [0.51544264 0.50649839]
 [0.51543668 0.50641396]
 [0.5155264  0.50715967]
 [0.5155294  0.5072021 ]]
[0.515435451586522, 0.515436430335071, 0.5154426379273293, 0.5154366757928045, 0.5155264005817642, 0.515529396703288]
          
chechehcehchehchhcehceh
[[0.51793198 0.50884808]
 [0.51799646 0.50896876]
 [0.51792181 0.50882905]
 [0.51839281 0.50992804]
 [0.51836169 0.50986979]
 [0.51793453 0.50885285]
 [0.5179175  0.50882099]]
[0.5179319779215661, 0.5179964640212611, 0.5179218103743777, 0.5183928145315854, 0.5183616915639693, 0.5179345278114238, 0.5179175017489327]
          
chechehcehchehchhcehceh
[[0.52059476 0.51158669]
 [0.52058626 0.5115737 ]
 [0.52055573 0.51152711]
 [0.52058

 10%|█         | 10/100 [00:00<00:06, 14.43it/s]

[[0.5247685  0.51660277]
 [0.52345228 0.51457696]
 [0.52373102 0.51497794]
 [0.52344727 0.51456975]
 [0.52358639 0.51476988]
 [0.52346331 0.51459282]
 [0.52340833 0.51451374]
 [0.524903   0.51679627]
 [0.52338971 0.51448694]]
[0.5247684970853433, 0.523452284242188, 0.5237310216341016, 0.5234472704495191, 0.5235863931208347, 0.5234633062213415, 0.5234083345126028, 0.5249029998875683, 0.5233897101742819]
          
chechehcehchehchhcehceh
[[0.52841209 0.52052708]
 [0.52647587 0.5177706 ]
 [0.52637031 0.51762493]
 [0.526341   0.51758448]
 [0.52649447 0.51779626]
 [0.52640173 0.51766829]
 [0.52694608 0.51841945]
 [0.5267021  0.51808278]
 [0.52863895 0.52084013]
 [0.52646742 0.51775893]]
[0.5284120908105581, 0.5264758737334514, 0.5263703144529908, 0.5263409986519905, 0.5264944671372104, 0.5264017328848045, 0.5269460758338527, 0.5267021048170417, 0.5286389471606612, 0.5264674157607537]
          
chechehcehchehchhcehceh
******
******
[[0.53042591 0.52221353]
 [0.53028499 0.52202521]
 [0.5301

 14%|█▍        | 14/100 [00:00<00:05, 14.57it/s]

[[0.53247494 0.52409595]
 [0.53326897 0.52512922]
 [0.53275293 0.5244577 ]
 [0.53253941 0.52417984]
 [0.53282598 0.52455276]
 [0.53277153 0.5244819 ]
 [0.53380537 0.52582725]
 [0.53257756 0.52422949]
 [0.53281241 0.5245351 ]
 [0.53679574 0.52973902]
 [0.53260849 0.52426975]
 [0.5362972  0.52909028]]
[0.5324749398038786, 0.5332689658688046, 0.5327529267702596, 0.5325394054026631, 0.5328259769529907, 0.5327715251095604, 0.5338053663600881, 0.5325775551577493, 0.5328124101690377, 0.5367957403205295, 0.5326084939352433, 0.5362972028718085]
          
chechehcehchehchhcehceh
[[0.53608136 0.52804712]
 [0.5356228  0.52746271]
 [0.53576224 0.52764041]
 [0.5360998  0.52807061]
 [0.53600054 0.52794411]
 [0.53743048 0.52976651]
 [0.53580428 0.52769399]
 [0.53602581 0.52797632]
 [0.53690511 0.52909695]
 [0.5367017  0.52883771]
 [0.5357104  0.52757435]
 [0.54051212 0.53369135]
 [0.54118922 0.53455426]]
[0.5360813614594114, 0.5356228047133887, 0.5357622411860686, 0.5360997956661313, 0.53600053651954

 18%|█▊        | 18/100 [00:01<00:05, 15.24it/s]

[[0.55515323 0.54993357]
 [0.54532121 0.53795597]
 [0.54610148 0.53891066]
 [0.55000027 0.54368085]
 [0.54550934 0.53818615]
 [0.55433419 0.54893168]
 [0.54542509 0.53808307]
 [0.55379918 0.5482772 ]
 [0.54876684 0.54217178]
 [0.54771472 0.54088451]
 [0.55591696 0.55086778]
 [0.5459026  0.53866732]
 [0.54514566 0.53774118]
 [0.54606454 0.53886547]
 [0.54595323 0.53872927]
 [0.5473073  0.54038602]]
[0.5551532286876292, 0.5453212119495234, 0.546101478227328, 0.5500002729383323, 0.5455093387586432, 0.5543341942630766, 0.5454250942166432, 0.5537991832252371, 0.5487668389451009, 0.5477147212727812, 0.5559169560009808, 0.5459025956983063, 0.5451456646988043, 0.546064542846455, 0.5459532315737861, 0.5473073011813597]
          
chechehcehchehchhcehceh
[[0.55375894 0.54786946]
 [0.55230821 0.54610611]
 [0.54825457 0.54117862]
 [0.55059129 0.54401913]
 [0.54912919 0.54224181]
 [0.55955143 0.55484579]
 [0.55361991 0.54770048]
 [0.55107058 0.54460173]
 [0.54917264 0.54229464]
 [0.55795955 0.55291

 20%|██        | 20/100 [00:01<00:05, 14.99it/s]

[0.5544093952290479, 0.5553389890271334, 0.5697774328874166, 0.5538547724763248, 0.5538383781904656, 0.5685823266650737, 0.5667520864142562, 0.5664625144036395, 0.5551062750705728, 0.5550267855066038, 0.5595209963857476, 0.5578706658290505, 0.5542771259651903, 0.5580929595607064, 0.5614549306783136, 0.5552810098407861, 0.5541140192683757, 0.5673002395404643, 0.561269620081649]
          
chechehcehchehchhcehceh
[[0.5607186  0.55548515]
 [0.57051558 0.56718361]
 [0.564183   0.55965661]
 [0.55655617 0.5504723 ]
 [0.56960234 0.5660845 ]
 [0.55607751 0.54989579]
 [0.57321572 0.5704328 ]
 [0.55765133 0.5517913 ]
 [0.55637823 0.55025798]
 [0.55771458 0.55186747]
 [0.57191312 0.56886543]
 [0.56991802 0.56646444]
 [0.557374   0.55145728]
 [0.56060159 0.55534425]
 [0.56227608 0.5573606 ]
 [0.55670047 0.55064609]
 [0.56438507 0.55989989]
 [0.56047614 0.55519318]
 [0.55977891 0.55435355]
 [0.55746072 0.55156172]]
[0.5607186003466997, 0.5705155822460162, 0.5641829978929148, 0.5565561697238007, 0.5

 24%|██▍       | 24/100 [00:01<00:05, 14.56it/s]

[[0.56889967 0.56446449]
 [0.58335199 0.58260496]
 [0.574784   0.57225438]
 [0.56489722 0.56042086]
 [0.56321936 0.55250273]
 [0.56694813 0.56290137]
 [0.57889732 0.57722478]
 [0.56517351 0.56075504]
 [0.57514343 0.5726888 ]
 [0.56689301 0.56283471]
 [0.57741472 0.57543353]
 [0.56504018 0.56059378]
 [0.56042929 0.55501595]
 [0.56167773 0.55652634]
 [0.56174983 0.55661356]
 [0.56146045 0.55626347]
 [0.56935063 0.56580664]
 [0.5605938  0.55521497]
 [0.56022643 0.55477051]
 [0.56410266 0.55945977]
 [0.55988359 0.55435572]
 [0.5613616  0.55614388]]
[0.568899669897609, 0.5833519916297342, 0.5747839968226508, 0.564897224278721, 0.5632193602941473, 0.5669481280985129, 0.5788973151959005, 0.5651735112894326, 0.5751434341047923, 0.5668930142905941, 0.5774147232821899, 0.5650401805198804, 0.5604292925999914, 0.5616777320206139, 0.56174982882458, 0.5614604458526185, 0.5693506328847515, 0.5605937962650002, 0.5602264312157204, 0.5641026596018233, 0.5598835941929525, 0.5613615968013308]
          
c

 28%|██▊       | 28/100 [00:01<00:04, 14.92it/s]

[[0.58083693 0.58065772]
 [0.57709947 0.57601458]
 [0.58354206 0.58401667]
 [0.57177302 0.56956715]
 [0.58527187 0.58616376]
 [0.56677831 0.56335497]
 [0.56443614 0.56044081]
 [0.57777685 0.5768563 ]
 [0.5632853  0.55900871]
 [0.56961075 0.56687823]
 [0.56312154 0.5588049 ]
 [0.57674159 0.57556984]
 [0.56414806 0.56008234]
 [0.56756926 0.56433892]
 [0.56404966 0.55995989]
 [0.56985919 0.56718722]
 [0.57936085 0.57882426]
 [0.56257828 0.55812882]
 [0.56784428 0.56468104]
 [0.57054881 0.56804484]
 [0.56812891 0.5650351 ]
 [0.56291958 0.55855358]
 [0.56955589 0.56681   ]
 [0.56436437 0.5603515 ]
 [0.56771156 0.56451594]
 [0.57200212 0.569852  ]]
[0.5808369308078185, 0.5770994700199233, 0.5840166697975063, 0.571773022914761, 0.5861637594176203, 0.5667783147607639, 0.5644361409357866, 0.5777768523214772, 0.5632853038214213, 0.5696107473144435, 0.563121537282299, 0.5767415947112002, 0.5641480610323434, 0.5675692555185979, 0.5640496567047167, 0.5698591940385868, 0.579360847424276, 0.562578280

 32%|███▏      | 32/100 [00:02<00:04, 15.48it/s]

[[0.5732075  0.57274305]
 [0.56876892 0.56721468]
 [0.56547219 0.56293736]
 [0.5800629  0.58162461]
 [0.57930317 0.58064093]
 [0.57449515 0.57441214]
 [0.57789566 0.5788181 ]
 [0.56777504 0.56592538]
 [0.57569536 0.57596755]
 [0.56130772 0.55753159]
 [0.57236609 0.57165219]
 [0.56281467 0.55948802]
 [0.56721524 0.56519911]
 [0.56174834 0.55810366]
 [0.56895493 0.56745596]
 [0.56535671 0.56278749]
 [0.57265694 0.57202928]
 [0.5655799  0.56307713]
 [0.56964527 0.56835134]
 [0.5762592  0.57669814]
 [0.56581088 0.56337688]
 [0.56258099 0.55918465]
 [0.56701357 0.56493746]
 [0.5647149  0.56195454]
 [0.56188117 0.55827612]
 [0.56275645 0.55941244]
 [0.56696904 0.56487968]
 [0.57930493 0.5806432 ]
 [0.56250116 0.55908103]
 [0.56158454 0.557891  ]]
[0.5732074992148145, 0.5687689230931757, 0.5654721916157109, 0.581624608930462, 0.5806409260840835, 0.5744951485228206, 0.5788181012935385, 0.5677750364228795, 0.5759675497966082, 0.5613077243711431, 0.5723660926295535, 0.5628146735096475, 0.5672152

 36%|███▌      | 36/100 [00:02<00:03, 16.66it/s]

[[0.55858928 0.55521487]
 [0.56801575 0.56780817]
 [0.55702792 0.55261306]
 [0.56242981 0.56046529]
 [0.56067283 0.55806369]
 [0.56225677 0.56022879]
 [0.56274551 0.56089674]
 [0.56717061 0.56665402]
 [0.56413817 0.56279978]
 [0.56228807 0.56027157]
 [0.57109319 0.57200914]
 [0.56301016 0.56125842]
 [0.56128057 0.55889448]
 [0.56365277 0.56213654]
 [0.55911792 0.55593776]
 [0.56567198 0.56460698]
 [0.56626416 0.56541593]
 [0.57128873 0.57227597]
 [0.56983184 0.57028762]
 [0.56144287 0.55911634]
 [0.57055764 0.57127826]
 [0.5582799  0.5547918 ]
 [0.56956572 0.56992435]
 [0.56282328 0.56100304]
 [0.57055888 0.57127995]
 [0.56120489 0.55879103]
 [0.56587666 0.5648866 ]
 [0.55933809 0.55623881]
 [0.56841287 0.56835042]
 [0.56352199 0.56195784]
 [0.55847426 0.55505759]
 [0.56112375 0.55868012]
 [0.55917397 0.55601441]
 [0.55868255 0.55534242]]
[0.5585892755443365, 0.5680157522056747, 0.5570279241913273, 0.5624298059623433, 0.5606728332027855, 0.562256769582241, 0.5627455057294849, 0.5671706

 40%|████      | 40/100 [00:02<00:03, 17.25it/s]

[[0.56156074 0.55983781]
 [0.55888596 0.5560857 ]
 [0.55859599 0.55567883]
 [0.56065262 0.55856411]
 [0.5614086  0.55962444]
 [0.56133766 0.55952495]
 [0.57025373 0.57166764]
 [0.56083893 0.55882545]
 [0.559434   0.55685462]
 [0.56863762 0.56940446]
 [0.56718393 0.567368  ]
 [0.56363231 0.56274252]
 [0.56285472 0.56165234]
 [0.55954951 0.55701666]
 [0.56278181 0.56155011]
 [0.56554124 0.56506599]
 [0.57062015 0.57218065]
 [0.56755636 0.56788981]
 [0.55877816 0.55593444]
 [0.56705216 0.56718337]
 [0.56248587 0.56113516]
 [0.55958783 0.55707043]
 [0.55938146 0.5567809 ]
 [0.56888722 0.56975406]
 [0.5630299  0.56189796]
 [0.56235301 0.56094885]
 [0.56956915 0.57070907]
 [0.56350971 0.56257064]
 [0.56639132 0.56625737]
 [0.57007032 0.57141083]
 [0.5612616  0.55941828]
 [0.5649859  0.56428758]
 [0.55897339 0.55620836]
 [0.56232367 0.56090771]
 [0.56558024 0.56512066]
 [0.56517785 0.56455664]
 [0.56956799 0.57070744]
 [0.56408734 0.56338041]]
[0.5615607368388627, 0.5588859641742712, 0.558595

 44%|████▍     | 44/100 [00:02<00:03, 16.32it/s]

[[0.56525118 0.56527275]
 [0.55934055 0.55720764]
 [0.55944741 0.55736111]
 [0.5589144  0.55659559]
 [0.56437735 0.56401892]
 [0.56446428 0.56414367]
 [0.56116745 0.55983097]
 [0.56586292 0.56615038]
 [0.56064038 0.55907422]
 [0.56250575 0.56175208]
 [0.55873379 0.55633617]
 [0.56598491 0.56632536]
 [0.56756177 0.56858691]
 [0.56311156 0.56262154]
 [0.56110182 0.55973674]
 [0.56216421 0.56126186]
 [0.56632969 0.56681992]
 [0.56756459 0.56859095]
 [0.56266759 0.56198437]
 [0.56243804 0.5616549 ]
 [0.56204127 0.56108539]
 [0.56882694 0.57040078]
 [0.55929194 0.55713783]
 [0.56412791 0.56366097]
 [0.55883352 0.55647942]
 [0.560468   0.5588267 ]
 [0.56819311 0.56949214]
 [0.56103145 0.55963571]
 [0.56450038 0.56419547]
 [0.56364607 0.56338857]
 [0.56201413 0.56104643]
 [0.563225   0.56278435]
 [0.5625055  0.56175173]
 [0.56916621 0.57088709]
 [0.56865712 0.57015735]
 [0.55856525 0.55609409]
 [0.56733068 0.56825554]
 [0.56130822 0.56003306]
 [0.56737861 0.56832427]
 [0.56395024 0.56340598]


 48%|████▊     | 48/100 [00:03<00:03, 17.10it/s]

[[0.55924161 0.55816605]
 [0.56099621 0.56027205]
 [0.55838934 0.55689474]
 [0.55809514 0.55645583]
 [0.55666103 0.55431596]
 [0.56139499 0.56086671]
 [0.56154874 0.56109598]
 [0.55711738 0.55499697]
 [0.5604309  0.55942893]
 [0.56394517 0.56466826]
 [0.56273854 0.56286984]
 [0.5618084  0.56148315]
 [0.56019533 0.55958841]
 [0.56145688 0.560959  ]
 [0.56321121 0.5635744 ]
 [0.55949842 0.55854908]
 [0.56035674 0.5598291 ]
 [0.56259844 0.562661  ]
 [0.55912868 0.55799762]
 [0.55722443 0.5551567 ]
 [0.55796546 0.55626236]
 [0.5635616  0.56409663]
 [0.5591491  0.55802808]
 [0.56321202 0.5635756 ]
 [0.55955405 0.55863206]
 [0.55653428 0.5541268 ]
 [0.55944765 0.55847337]
 [0.55844228 0.55697372]
 [0.56040371 0.55938839]
 [0.55673604 0.5544279 ]
 [0.56003985 0.55935656]
 [0.5594986  0.55854936]
 [0.56273641 0.56286667]
 [0.55859756 0.55720536]
 [0.55995448 0.55922925]
 [0.55962039 0.558731  ]
 [0.56412945 0.56494286]
 [0.55719776 0.5551169 ]
 [0.56033827 0.55929077]
 [0.5600167  0.55881113]


 52%|█████▏    | 52/100 [00:03<00:02, 16.42it/s]

[[0.55428654 0.55232566]
 [0.55520323 0.55310314]
 [0.55343562 0.55098785]
 [0.55422565 0.55222994]
 [0.55652336 0.55517829]
 [0.55483655 0.55319026]
 [0.55674424 0.55552543]
 [0.55477536 0.55309408]
 [0.55416682 0.55213745]
 [0.55419726 0.55218531]
 [0.55594805 0.55427403]
 [0.55472137 0.55234553]
 [0.54852851 0.54862722]
 [0.55475887 0.55306816]
 [0.55460368 0.55282421]
 [0.55465687 0.55290782]
 [0.5538261  0.54705456]
 [0.55506685 0.55355224]
 [0.55317333 0.55057542]
 [0.55504666 0.55285698]
 [0.55632161 0.5548612 ]
 [0.55599434 0.55434679]
 [0.55470573 0.55232094]
 [0.55632208 0.55486193]
 [0.55399767 0.55187154]
 [0.55536463 0.55335688]
 [0.55480466 0.55314013]
 [0.55520537 0.55376997]
 [0.55466807 0.55226173]
 [0.55531176 0.55327377]
 [0.55604948 0.55443346]
 [0.55310048 0.55046087]
 [0.55349715 0.55108459]
 [0.5548747  0.55325022]
 [0.55596883 0.55430669]
 [0.55685036 0.55569221]
 [0.55604826 0.55443154]
 [0.55502517 0.55348673]
 [0.55321644 0.55064321]
 [0.55527614 0.55321777]


 54%|█████▍    | 54/100 [00:03<00:02, 16.37it/s]

[[0.55169025 0.54878983]
 [0.55026463 0.54440095]
 [0.55152725 0.54934954]
 [0.55145183 0.54837157]
 [0.55108685 0.54778021]
 [0.5505016  0.54769212]
 [0.55147823 0.54927032]
 [0.55133442 0.54903795]
 [0.55125061 0.54890253]
 [0.55101471 0.54852134]
 [0.55198709 0.54931053]
 [0.55064487 0.54792366]
 [0.55060858 0.54786502]
 [0.55134332 0.54905234]
 [0.55127933 0.54894895]
 [0.55090891 0.54802177]
 [0.55065315 0.54793704]
 [0.55157555 0.54942757]
 [0.55121538 0.54798798]
 [0.55148294 0.54842616]
 [0.55168456 0.54960371]
 [0.55065846 0.54708771]
 [0.55110609 0.54781132]
 [0.55162569 0.54950859]
 [0.55104746 0.54771655]
 [0.55096288 0.54757982]
 [0.55170327 0.54881267]
 [0.55151919 0.54848975]
 [0.55150074 0.54930669]
 [0.55152001 0.54849119]
 [0.55070003 0.5471549 ]
 [0.55183859 0.54905005]
 [0.550439   0.54759095]
 [0.55107936 0.5486258 ]
 [0.55075839 0.54724925]
 [0.55113465 0.54785748]
 [0.55170296 0.54881212]
 [0.55052047 0.54772262]
 [0.55103115 0.5485479 ]
 [0.5514658  0.54839608]


 60%|██████    | 60/100 [00:03<00:02, 17.44it/s]

[[0.54642718 0.54208535]
 [0.5467622  0.5436575 ]
 [0.54648621 0.54221449]
 [0.54676778 0.54366235]
 [0.54659389 0.54245006]
 [0.54684621 0.54373059]
 [0.54687736 0.54375769]
 [0.54687646 0.54375691]
 [0.54644913 0.54213338]
 [0.54681782 0.54293992]
 [0.54690966 0.54378579]
 [0.5470235  0.54108337]
 [0.54661905 0.54250512]
 [0.54659904 0.54246134]
 [0.54684388 0.54372857]
 [0.54627635 0.54175536]
 [0.54679148 0.5428823 ]
 [0.54679258 0.54368393]
 [0.54668659 0.54265285]
 [0.54668189 0.54264258]
 [0.54640909 0.54204579]
 [0.54677376 0.54366756]
 [0.54679141 0.54368291]
 [0.54660537 0.54247518]
 [0.54688143 0.54376124]
 [0.54635827 0.54193459]
 [0.54655908 0.54298878]
 [0.54689275 0.54377108]
 [0.54688925 0.54376804]
 [0.54682521 0.54371232]
 [0.54689051 0.54376914]
 [0.54693058 0.543804  ]
 [0.54678626 0.54367843]
 [0.54691661 0.54379185]
 [0.54683092 0.54371729]
 [0.54685306 0.54373655]
 [0.54673666 0.54276238]
 [0.54624955 0.54169673]
 [0.54692347 0.54379781]
 [0.54623046 0.54165497]


 62%|██████▏   | 62/100 [00:03<00:02, 16.11it/s]

******
******
[[0.54178958 0.53798567]
 [0.54180151 0.53799548]
 [0.54181345 0.53800528]
 [0.54182538 0.53801508]
 [0.54185835 0.53809716]
 [0.5419109  0.53824651]
 [0.54196345 0.53839584]
 [0.54201599 0.53854518]
 [0.54206854 0.5386945 ]
 [0.54212108 0.53884382]]
[[0.54179301 0.5379885 ]
 [0.54196294 0.53839442]
 [0.54121473 0.53606455]
 [0.54114479 0.53601664]
 [0.54119509 0.5360511 ]
 [0.54179135 0.53798713]
 [0.54181559 0.53800704]
 [0.54176731 0.53796738]
 [0.54180347 0.53799709]
 [0.54123822 0.53608065]
 [0.54116133 0.53602797]
 [0.54115841 0.53602596]
 [0.54124234 0.53608347]
 [0.54182622 0.53801577]
 [0.5418007  0.53799481]
 [0.54201925 0.53855442]
 [0.54112111 0.53600041]
 [0.54179453 0.53798975]
 [0.54116381 0.53602967]
 [0.54122957 0.53607472]
 [0.54114381 0.53601596]
 [0.54180409 0.53799759]
 [0.54184825 0.53806845]
 [0.54123243 0.53607668]
 [0.54198186 0.53844816]
 [0.54205382 0.53865267]
 [0.54177214 0.53797135]
 [0.54174473 0.53794884]
 [0.54114378 0.53601594]
 [0.541781

 66%|██████▌   | 66/100 [00:04<00:01, 17.02it/s]

[[0.53759753 0.53359787]
 [0.53715292 0.53264184]
 [0.53780054 0.53423967]
 [0.53715292 0.53264184]
 [0.53715292 0.53264184]
 [0.53715292 0.53264184]
 [0.53768458 0.53384529]
 [0.53777839 0.53416434]
 [0.53715292 0.53264184]
 [0.53715292 0.53264184]
 [0.53745463 0.53322997]
 [0.53748532 0.53330898]
 [0.53748531 0.53330894]
 [0.53750072 0.53334863]
 [0.53757402 0.53353732]
 [0.53742957 0.53316543]
 [0.53715292 0.53264184]
 [0.53770502 0.53391481]
 [0.53715292 0.53264184]
 [0.53735633 0.53297687]
 [0.53715292 0.53264184]
 [0.53715292 0.53264184]
 [0.53715292 0.53264184]
 [0.5375149  0.53338512]
 [0.53715292 0.53264184]
 [0.53755737 0.53349446]
 [0.53715292 0.53264184]
 [0.53748938 0.53331944]
 [0.53767991 0.53382943]
 [0.53715292 0.53264184]
 [0.53775465 0.5340836 ]
 [0.53715292 0.53264184]
 [0.53715292 0.53264184]
 [0.53756583 0.53351626]
 [0.53762242 0.53366192]
 [0.53744884 0.53321505]
 [0.53715292 0.53264184]
 [0.53748087 0.53329752]
 [0.53715292 0.53264184]
 [0.5376079  0.53362456]


 70%|███████   | 70/100 [00:04<00:01, 17.22it/s]

[[0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53231555 0.52850032]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53234339 0.52868672]
 [0.53217072 0.52832622]
 [0.53231431 0.52849182]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53231928 0.52852594]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53233696 0.5286475 ]
 [0.53217072 0.52832622]
 [0.53221889 0.52835249]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53217072 0.52832622]
 [0.53225231 0.52837071]
 [0.53217072 0.52832622]


 72%|███████▏  | 72/100 [00:04<00:01, 14.82it/s]

[[0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.52872417 0.5253517 ]
 [0.5286467  0.5253156 ]
 [0.52874805 0.52536282]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.52871004 0.52534511]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.5286467  0.5253156 ]
 [0.52869857 0.52533977]
 [0.5286467  0.5253156 ]


 76%|███████▌  | 76/100 [00:04<00:01, 15.46it/s]

[[0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886 0.5223666]
 [0.5251886

 80%|████████  | 80/100 [00:05<00:01, 16.62it/s]

[[0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]
 [0.52014483 0.51798376]


 84%|████████▍ | 84/100 [00:05<00:00, 16.69it/s]

[[0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]
 [0.51493404 0.5133837 ]


 88%|████████▊ | 88/100 [00:05<00:00, 17.30it/s]

[[0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]
 [0.51019987 0.50918024]


 92%|█████████▏| 92/100 [00:05<00:00, 16.38it/s]

[[0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]
 [0.50635827 0.50577196]


 96%|█████████▌| 96/100 [00:05<00:00, 17.04it/s]

[[0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]
 [0.50399735 0.50372957]


100%|██████████| 100/100 [00:06<00:00, 17.25it/s]

[[0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]
 [0.50354084 0.50346871]


In [ ]:
pred_guess_0