In [26]:
import tensorflow as tf
import numpy as np


class Actor(tf.keras.Model):
    def __init__(self):
        super(Actor,self).__init__()
        self.lstm = tf.keras.layers.LSTM(5, return_sequences=True, stateful=True,batch_size=1, input_shape=(1,1))#, input_shape=(None,None,1))
        
    def call(self, inputs):
        feat= self.lstm(inputs)
        return feat



In [70]:
actor = Actor()

In [30]:
actor.compile()

In [32]:
actor.lstm.input_spec

[InputSpec(ndim=3)]

In [42]:
actor = Actor()
context1 = tf.reshape(np.array([0.]*10),(10,1,1))
actor(context1)

<tf.Tensor: shape=(10, 1, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]]], dtype=float32)>

In [43]:

actor(context1)
actor.reset_states()
actor.lstm.stateful=True


In [44]:
context = tf.reshape(np.array([0.]),(1,1,1))
actor(context)


<tf.Tensor: shape=(1, 1, 5), dtype=float32, numpy=array([[[0., 0., 0., 0., 0.]]], dtype=float32)>

In [47]:
actor.lstm.stateful

False

In [48]:
actor.lstm.stateful=True

In [49]:
context = tf.reshape(np.array([0.]*5),(5,1,1))

In [51]:
context

<tf.Tensor: shape=(5, 1, 1), dtype=float64, numpy=
array([[[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]]])>

In [54]:
actor.lstm.stateful = True

In [57]:
actor(context1)

<tf.Tensor: shape=(10, 1, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]]], dtype=float32)>

In [58]:
actor.lstm.reset_states()

In [59]:
actor(context)

InvalidArgumentError: Incompatible shapes: [5,20] vs. [10,20] [Op:AddV2]

In [68]:
actor.lstm.state_spec[0]

InputSpec(shape=(None, 5), ndim=2)

In [147]:
actor = Actor()

In [148]:

@tf.function
def g(actor):
    context1 = tf.reshape(np.array([0.]*10),(10,1,1))
    actor(context1)
g(actor)    


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [149]:
actor.lstm.states = 

[<tf.Variable 'actor_18/lstm_17/Variable:0' shape=(10, 5) dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Variable 'actor_18/lstm_17/Variable:0' shape=(10, 5) dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>]

<tf.Tensor: shape=(10, 1, 1), dtype=float64, numpy=
array([[[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]]])>

In [8]:
actor.trainable_variables

[<tf.Variable 'actor_2/lstm_2/lstm_cell_2/kernel:0' shape=(1, 20) dtype=float32, numpy=
 array([[-0.36921751, -0.309299  , -0.29241025, -0.08891496, -0.04902607,
          0.12503302,  0.30231136,  0.15895498, -0.18136916, -0.12902302,
          0.4817037 , -0.4604325 ,  0.15868217, -0.01586515,  0.37037134,
         -0.46790916, -0.20835128,  0.17915171,  0.389566  , -0.53107214]],
       dtype=float32)>,
 <tf.Variable 'actor_2/lstm_2/lstm_cell_2/recurrent_kernel:0' shape=(5, 20) dtype=float32, numpy=
 array([[-0.2583412 , -0.24075477,  0.1899779 ,  0.21819398,  0.22574756,
         -0.02066391,  0.18682563,  0.17479512,  0.38013914, -0.2790149 ,
         -0.08371739, -0.04322455, -0.4772173 ,  0.04387664,  0.25090107,
         -0.1142222 ,  0.18592629, -0.04514169, -0.23136489,  0.2184559 ],
        [-0.06825901, -0.32771975,  0.40122917, -0.05473512, -0.18172969,
         -0.27114928, -0.09661461,  0.28397095,  0.0357779 ,  0.18460394,
          0.057315  ,  0.43625468, -0.04464725,

In [9]:
actor = Actor()
context1 = tf.reshape(np.array([0.]*1),(1,1,1))
actor(context1)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



<tf.Tensor: shape=(1, 1, 5), dtype=float32, numpy=array([[[0., 0., 0., 0., 0.]]], dtype=float32)>

In [10]:
actor.trainable_variables

[<tf.Variable 'actor_3/lstm_3/lstm_cell_3/kernel:0' shape=(1, 20) dtype=float32, numpy=
 array([[ 0.29354918,  0.42474687, -0.46439028,  0.06854546,  0.24051768,
         -0.178763  , -0.05955046,  0.16232389, -0.4465729 ,  0.5152603 ,
         -0.04619154, -0.1350554 ,  0.37292385,  0.3340934 , -0.17380801,
          0.00687933, -0.27338755, -0.24165127,  0.18090671, -0.21051154]],
       dtype=float32)>,
 <tf.Variable 'actor_3/lstm_3/lstm_cell_3/recurrent_kernel:0' shape=(5, 20) dtype=float32, numpy=
 array([[-0.20712054,  0.08432765,  0.26818874,  0.19513772, -0.08016415,
         -0.11688738, -0.30079988, -0.19023935,  0.2822461 ,  0.2834833 ,
         -0.0392952 , -0.11641802,  0.10284983, -0.31647983,  0.31684077,
          0.07019372, -0.10080176, -0.24220233, -0.10315619,  0.4717898 ],
        [-0.26826516, -0.15284304,  0.01706141,  0.08783561,  0.06904048,
         -0.4265074 ,  0.26550025,  0.14109884,  0.37763855,  0.09548451,
          0.17851816, -0.04021922, -0.01234288,

In [11]:
actor.lstm.input_spec

[InputSpec(shape=(1, None, 1), ndim=3)]

In [96]:
actor = Actor()

In [97]:
actor.lstm.states

[None, None]

In [98]:
actor.lstm.input_spec

[InputSpec(ndim=3)]

In [99]:
context1 = tf.random.uniform((10,1,1))

In [100]:
actor(context1)

<tf.Tensor: shape=(10, 1, 5), dtype=float32, numpy=
array([[[ 0.00689401, -0.00623817, -0.00031287,  0.0028284 ,
          0.00438953]],

       [[ 0.09127401, -0.07122415, -0.00404871,  0.04259438,
          0.06519401]],

       [[ 0.09249331, -0.07198254, -0.00410485,  0.04328476,
          0.06619596]],

       [[ 0.10380597, -0.07868154, -0.00463609,  0.04996729,
          0.07571269]],

       [[ 0.02085456, -0.01846709, -0.00093682,  0.00868439,
          0.01350065]],

       [[ 0.05003494, -0.04224258, -0.00221681,  0.02164167,
          0.03362429]],

       [[ 0.06947888, -0.05665234, -0.00306934,  0.03102225,
          0.04798682]],

       [[ 0.0924693 , -0.07196768, -0.00410375,  0.04327111,
          0.06617618]],

       [[ 0.09547301, -0.07380746, -0.00424288,  0.04499476,
          0.06866346]],

       [[ 0.10066997, -0.07688885, -0.00448674,  0.04806083,
          0.07303344]]], dtype=float32)>

In [101]:
actor.lstm.states

[<tf.Variable 'actor_13/lstm_12/Variable:0' shape=(10, 5) dtype=float32, numpy=
 array([[ 0.00689401, -0.00623817, -0.00031287,  0.0028284 ,  0.00438953],
        [ 0.09127401, -0.07122415, -0.00404871,  0.04259438,  0.06519401],
        [ 0.09249331, -0.07198254, -0.00410485,  0.04328476,  0.06619596],
        [ 0.10380597, -0.07868154, -0.00463609,  0.04996729,  0.07571269],
        [ 0.02085456, -0.01846709, -0.00093682,  0.00868439,  0.01350065],
        [ 0.05003494, -0.04224258, -0.00221681,  0.02164167,  0.03362429],
        [ 0.06947888, -0.05665234, -0.00306934,  0.03102225,  0.04798682],
        [ 0.0924693 , -0.07196768, -0.00410375,  0.04327111,  0.06617618],
        [ 0.09547301, -0.07380746, -0.00424288,  0.04499476,  0.06866346],
        [ 0.10066997, -0.07688885, -0.00448674,  0.04806083,  0.07303344]],
       dtype=float32)>,
 <tf.Variable 'actor_13/lstm_12/Variable:0' shape=(10, 5) dtype=float32, numpy=
 array([[ 0.0138493 , -0.01254076, -0.00062882,  0.00559438,  0.0

In [102]:
actor.lstm.input_spec

[InputSpec(shape=(10, None, 1), ndim=3)]

In [103]:
actor.lstm.reset_states()

In [104]:
actor.lstm.input_spec

[InputSpec(shape=(10, None, 1), ndim=3)]

In [88]:
actor.lstm.states = [None,None]

In [89]:
actor.lstm.input_spec

[InputSpec(shape=(10, None, 1), ndim=3)]

In [90]:
actor.lstm.input_spec=[tf.keras.layers.InputSpec(ndim=3)]

In [91]:
actor.lstm.input_spec

[InputSpec(ndim=3)]

In [94]:
actor.lstm.states

[None, None]

In [95]:
actor.reset_states()

ValueError: If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors: 
- If using a Sequential model, specify the batch size by passing a `batch_input_shape` argument to your first layer.
- If using the functional API, specify the batch size by passing a `batch_shape` argument to your Input layer.

In [105]:
actor1 = Actor()

In [109]:
actor1.lstm.stateful=False

In [108]:
actor1.lstm.states

[None, None]

In [110]:
actor1(context1)

<tf.Tensor: shape=(10, 1, 5), dtype=float32, numpy=
array([[[-0.00684307,  0.00459225, -0.00683068, -0.00420179,
         -0.00641246]],

       [[-0.12071112,  0.05367943, -0.1279011 , -0.04863315,
         -0.07169218]],

       [[-0.12293226,  0.05428739, -0.13036227, -0.04917773,
         -0.0724217 ]],

       [[-0.14479296,  0.05974866, -0.15471464, -0.05406183,
         -0.07878762]],

       [[-0.02161286,  0.01361223, -0.02179383, -0.01243209,
         -0.01893642]],

       [[-0.05695498,  0.03131739, -0.05864314, -0.02850113,
         -0.04305071]],

       [[-0.08458205,  0.04226924, -0.08828605, -0.03838435,
         -0.05743993]],

       [[-0.12288829,  0.05427546, -0.13031355, -0.04916703,
         -0.07240741]],

       [[-0.12846424,  0.05575803, -0.1365033 , -0.05049438,
         -0.07417057]],

       [[-0.13849035,  0.05826904, -0.14767125, -0.05274005,
         -0.07709966]]], dtype=float32)>

In [111]:
actor1.lstm.states

[None, None]

In [132]:
actor=Actor()
actor.lstm.stateful=False

In [133]:
actor(inn)

<tf.Tensor: shape=(10, 1, 5), dtype=float32, numpy=
array([[[-4.82265092e-03,  4.53974324e-04, -4.93532680e-05,
          5.88829909e-03, -2.87816976e-03]],

       [[-3.29558514e-02,  3.32604279e-03, -3.54190532e-04,
          4.26984988e-02, -2.39205528e-02]],

       [[-3.97181883e-02,  4.09035943e-03, -4.33340349e-04,
          5.22233248e-02, -3.03542670e-02]],

       [[-2.41116378e-02,  2.37533054e-03, -2.54627550e-04,
          3.06544229e-02, -1.64089333e-02]],

       [[-1.51925208e-02,  1.46389299e-03, -1.57955597e-04,
          1.89553853e-02, -9.71657317e-03]],

       [[-1.38325403e-02,  1.32859254e-03, -1.43498502e-04,
          1.72094796e-02, -8.76535941e-03]],

       [[-7.44857714e-02,  8.81840102e-03, -9.07490496e-04,
          1.06463864e-01, -7.79333636e-02]],

       [[-2.17144452e-02,  2.12604110e-03, -2.28308432e-04,
          2.74670124e-02, -1.45291341e-02]],

       [[-6.09638821e-03,  5.75449958e-04, -6.25020184e-05,
          7.46324239e-03, -3.66883120e-0

In [116]:
actor.lstm.input_spec

[InputSpec(shape=(None, None, 1), ndim=3)]

In [115]:
actor.lstm.stateful

False

In [139]:
actor.lstm.states

[None, None]

In [140]:
actor.lstm.stateful=True

In [136]:
actor.stateful

True

In [137]:
inn = tf.random.uniform((10,1,1))

In [138]:
actor(inn)

AttributeError: 'NoneType' object has no attribute 'shape'